### ISSUE TITLE
SSOT History Unknown filter field: overview

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-ssot-ipfabric#125]
### Environment
* Python version:  3.9
* Nautobot version:  1.5.10
* nautobot-ssot version:  1.2.0
* nautobot-ssot-ipfabric version:  2.0.0

### Expected Behavior

Brings me to a filtered table for the history of a job and a specific action

### Observed Behavior

URL: `/plugins/ssot/logs/?overview=15cbe6d1-a0c3-4379-a17a-d7c2f2f4e16c&action=create`

```
Invalid filters were specified:
overview
Unknown filter field
```

### Steps to Reproduce
1. Go to Plugins > SSOT History
2. Click one of the numbered links in Create/Update/Delete/Failure/Error columns
3.

**Comment by justinjeffery-ipf** [comment]
I think it is supposed to redirect to:
`/plugins/ssot/history/15cbe6d1-a0c3-4379-a17a-d7c2f2f4e16c/logs/?action=create`

**Comment by alhogan** [comment]
I have validated that this was an issue with nautobot-ssot and has been resolved.
