### ISSUE TITLE
Migration Announcement

### ISSUE THREAD

**Issue by alhogan** [nautobot/nautobot-plugin-ssot-ipfabric#141]
# The code in this repository has been migrated to the [Nautobot SSoT Repository](https://github.com/nautobot/nautobot-plugin-ssot) as an integration - read more about it in the [SSoT Docs](https://docs.nautobot.com/projects/ssot/en/latest/admin/install/)! As of August 2023 this repository has been **FROZEN** - all development / issues / discussions for this integration are in the [Nautobot SSoT Repository](https://github.com/nautobot/nautobot-plugin-ssot) going forward.

**Comment by jdrew82** [comment]
This isn't needed as it's in README.
