### ISSUE TITLE
Device Role

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-ssot-ipfabric#72]
### Environment

* nautobot version: 1.5.x
* nautobot-ssot-ipfabric version:  2.0.0
* ipfabric version: 6.x

### Summary

IP Fabric classifies devices into different "Types" (column `devType`) which can be used as a Nautobot `Device Role`.  Currently all devices are sync'ed using the default:

```
DEFAULT_DEVICE_ROLE = CONFIG.get("default_device_role", "Network Device")
DEFAULT_DEVICE_ROLE_COLOR = CONFIG.get("default_device_role_color", "ff0000")
```

### Proposed Functionality

- Have an option in `nautobot_config.py` that enables syncing the IP Fabric Device Type to Nautobot Device Role.
  - Device Types are mainly static and rarely change. Usually new types are added and normally none are removed.
  - Perhaps we just create new roles if it does not exist, and do not delete any roles.
- IPF Device Type is found at:
  - API: `FQDN/api/v#.#/tables/inventory/devices`
  - UI: `FQDN/inventory/devices`
  - Column: `devType`

```shell
> devices = ipf.inventory.devices.all()
> dev_type = {d['devType'] for d in devices}
> print(dev_type)
{'switch', 'fw', 'waas', 'wlc', 'lb', 'l3switch', 'router'}
```

### Open Questions

- Default to Enabled or Disabled sync'ing type to role?
- How do we map Device Role to a color?
  - Manually in UI after creation?
  - Allow for a config setting?
  - Create static example?

### Use Case

- "Role of `Network Device` is too generic."

### Current Device Types

List of Device Types in IP Fabric v6.2.1 is shown below.  Not all are used for `Network Device Inventory` purposes.  For instance `host` is used for IPF discovered hosts.

```python
[
  'aciLeaf',
  'aciSpine',
  'ap',
  'apic',
  'cloudInstance',
  'cloudInternetGw',
  'cloudLoadBalancer',
  'cloudNatGw',
  'cloudRouter',
  'cloudTransitHub',
  'cloudVpnGw',
  'fex',
  'fw',
  'host',
  'l3switch',
  'lb',
  'nx7000',
  'phone',
  'router',
  'securityManagement',
  'switch',
  'unknown',
  'vgw',
  'waas',
  'wlc',
]
```

**Comment by justinjeffery-ipf** [comment]
Or should this be a tag not a role?

**Comment by collinsjas** [comment]
This should be a role. Role of Network Device is too generic.

**Comment by pke11y** [comment]
The ipfabric `dev_type` looks good as a `Device Role`

**Comment by alhogan** [comment]
This feature will be included in the next release of nautobot-ssot with the inclusion of the ipfabric integration.
